name: Release
 on: 
   push:
      branches:
        - v1

 permissions:
  contents: read       

jobs: 
   release:
    runs-on: ubuntu-latest

steps:
-name: checkout
uses: actions/checkout@v3
with:
          fetch-depth: 0

             - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Copy .releaserc
        run: cp .github/.releaserc.yml .

      - name: Npm install
        run: npm i -g semantic-release @semantic-release/changelog @semantic-release/git

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release

